# safelist
branches:
  only:
  - dev
  - master

# Needed for docker
sudo: required
services: docker

# updating packages before start
before_install:
  - sudo apt-get update -qq

# build matrix
matrix:
  rvm: 2.5.0
  gemfile: Gemfile

before_script:
  # Print out docker info
  - docker --version
  - docker info
  - rubocop -c .rubocop.yml

script:
  # Run tests
  - kitchen test


  after_script:
  # Print out debug information
  - docker images
  - docker ps -a
  - cat .kitchen/logs/*kitchen*.log