
# Needed for docker
sudo: required

services: docker

# install the stable release of chefdk
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

# We don't need to install our gems as it comes from chefdk above
install: ./install-dependencies

env:
  matrix:
  - INSTANCE=default-centos-6

before_script:
# Print out docker info
- docker --version
- docker info
# Setup chefdk (Initialize your shell to use ChefDK as your primary ruby)
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
# Install test kitchen docker integration
- /opt/chefdk/embedded/bin/chef gem install kitchen-docker

script:
# Run tests
- /opt/chefdk/embedded/bin/chef --version
- /opt/chefdk/embedded/bin/foodcritic . -f any
- /opt/chefdk/embedded/bin/opt/chefdk/embedded/bin/chef gem install kitchen-docker/
# Run test kitchen using .kitchen.docker.yml instead of default .kitchen.yml
- KITCHEN_YAML=.kitchen.yml kitchen verify ${INSTANCE}

after_script:
# Print out debug information
- docker images
- docker ps -a
- cat .kitchen/logs/*kitchen*.log
