version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run:
        name: Gem setup
        command: |
          gem install bundler
          gem update --system
          bundle install
      - run:
          name: Kitchen Test
          command: KITCHEN_YAML=".kitchen.docker.yml" kitchen test
workflows:
  version: 2
  build:
    jobs:
    - build
