version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run:
          name: Gem setup
          command: |
            gem update --system
            gem install rubocop
      - run:
          name: Rubocop run
          command: rubocop -c .rubocop.yml
  test:
    machine:
      enabled: true
      image: circleci/classic:latest
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Gem setup
          command: |
            gem update --system

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
